### ISSUE TITLE
1/18 프론트 할 일

### ISSUE THREAD

**Issue by okhan1998** [Jo-and-Yu/React-CRM-Project#13]
## 목적
>대쉬보드 페이지, 카드, 차트, 테이블 추가  
## 작업 상세 내용
- [x] Make Dashboard page
- [x] Make Status Card 
- [x] Add Apexcharts
- [x] Make Table

**Comment by yeonah98** [comment]
너무 수고하셨습니당!
Apexchart 버그는 다음에 다시 확인합시당 :)
